### PR TITLE
Mobile app crypto

### PR DESCRIPTION
**Pull request by rega1237**
## in this branch:
- Built the structure
- Added the store and reducer
- Added the functionality to call the API and fetch the data
- Added dynamic route for the coins
- Added style to the mobile app
- Make the test

Loom Video: https://www.loom.com/share/a4c473a3bc614493932e46deb349f9a8

### CODE REVIEW

**Comment by omar-labana** [comment]
@rega1237 interesting choice for filtering coins, would like to suggest to implement nested filters(rank and name with filter queries) if possible. Also, I'm not so sure about the error msgs when coins are not yet fetched and the user have to navigate to main route to get it fetched, for this one I suggest that you fetch the data with a loader from the root component of your project and display the loader while fetching then if the coin doesn't exist you should display the error msg.

**Comment by omar-labana** [comment]
# **Approved ✔️**

Hi @rega1237 

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-labana** [comment]
https://www.youtube.com/watch?v=-wfwqzAu90g

**Comment by rega1237** [comment]
Hi @omar-labana thanks for the review, Yeah I was thinking about that, implement a search bar to also search by coin name, if I place an action call to fetch also in the details coin, is it ok? I mean that way the error will not appear if I go directly to the page with the domain for example "/details/bitcoin" because I will always have the state of the store with the 100 elements, it would only show the error if the currency as such is not in the state.

**Pull request merged**
